# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Netdata
version: 1.46.0
slug: netdata
description:
  Monitor your servers, containers, and applications, in high-resolution and in
  real-time
url: "https://github.com/felipecrs/netdata-hass-addon/tree/main/netdata"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  hostname: homeassistant
  netdata_claim_url: https://app.netdata.cloud
  netdata_claim_token: ""
  netdata_claim_rooms: ""
  netdata_extra_deb_packages: ""
  netdata_healthcheck_target: ""
schema:
  hostname: str
  netdata_claim_url: str
  netdata_claim_token: str
  netdata_claim_rooms: str
  netdata_extra_deb_packages: str
  netdata_healthcheck_target: str
startup: services
ingress: true
ingress_port: 19999
ingress_stream: true
init: false
panel_icon: mdi:leaf
panel_title: Netdata
host_pid: true
host_network: true
host_dbus: true
apparmor: false
journald: true
docker_api: true
privileged:
  - SYS_PTRACE
  - SYS_ADMIN
  # To allow run.sh to create mount points
  - SYS_RAWIO
map:
  - config:rw
